import 'package:flutter/material.dart';
import 'package:world_time/services/world_time.dart';

class ChooseLocation extends StatefulWidget {
  const ChooseLocation({super.key});

  @override
  State<ChooseLocation> createState() => _ChooseLocationState();
}

class _ChooseLocationState extends State<ChooseLocation> {

  List<WorldTime> locations = [
  WorldTime(location: "Africa-Abidjan", flag: 'ci.png', url: 'Africa/Abidjan'),
  WorldTime(location: "Africa-Accra", flag: 'gh.png', url: 'Africa/Accra'),
  WorldTime(location: "Africa-Addis Ababa", flag: 'et.png', url: 'Africa/Addis_Ababa'),
  WorldTime(location: "Africa-Algiers", flag: 'dz.png', url: 'Africa/Algiers'),
  WorldTime(location: "Africa-Asmara", flag: 'er.png', url: 'Africa/Asmara'),
  WorldTime(location: "Africa-Bamako", flag: 'ml.png', url: 'Africa/Bamako'),
  WorldTime(location: "Africa-Bangui", flag: 'cf.png', url: 'Africa/Bangui'),
  WorldTime(location: "Africa-Banjul", flag: 'gm.png', url: 'Africa/Banjul'),
  WorldTime(location: "Africa-Bissau", flag: 'gw.png', url: 'Africa/Bissau'),
  WorldTime(location: "Africa-Blantyre", flag: 'mw.png', url: 'Africa/Blantyre'),
  WorldTime(location: "Africa-Brazzaville", flag: 'cg.png', url: 'Africa/Brazzaville'),
  WorldTime(location: "Africa-Bujumbura", flag: 'bi.png', url: 'Africa/Bujumbura'),
  WorldTime(location: "Africa-Cairo", flag: 'eg.png', url: 'Africa/Cairo'),
  WorldTime(location: "Africa-Casablanca", flag: 'ma.png', url: 'Africa/Casablanca'),
  WorldTime(location: "Africa-Ceuta", flag: 'es.png', url: 'Africa/Ceuta'),
  WorldTime(location: "Africa-Conakry", flag: 'gn.png', url: 'Africa/Conakry'),
  WorldTime(location: "Africa-Dakar", flag: 'sn.png', url: 'Africa/Dakar'),
  WorldTime(location: "Africa-Dar es Salaam", flag: 'tz.png', url: 'Africa/Dar_es_Salaam'),
  WorldTime(location: "Africa-Djibouti", flag: 'dj.png', url: 'Africa/Djibouti'),
  WorldTime(location: "Africa-Douala", flag: 'cm.png', url: 'Africa/Douala'),
  WorldTime(location: "Africa-El Aaiun", flag: 'eh.png', url: 'Africa/El_Aaiun'),
  WorldTime(location: "Africa-Freetown", flag: 'sl.png', url: 'Africa/Freetown'),
  WorldTime(location: "Africa-Gaborone", flag: 'bw.png', url: 'Africa/Gaborone'),
  WorldTime(location: "Africa-Harare", flag: 'zw.png', url: 'Africa/Harare'),
  WorldTime(location: "Africa-Johannesburg", flag: 'za.png', url: 'Africa/Johannesburg'),
  WorldTime(location: "Africa-Juba", flag: 'ss.png', url: 'Africa/Juba'),
  WorldTime(location: "Africa-Kampala", flag: 'ug.png', url: 'Africa/Kampala'),
  WorldTime(location: "Africa-Khartoum", flag: 'sd.png', url: 'Africa/Khartoum'),
  WorldTime(location: "Africa-Kigali", flag: 'rw.png', url: 'Africa/Kigali'),
  WorldTime(location: "Africa-Kinshasa", flag: 'cd.png', url: 'Africa/Kinshasa'),
  WorldTime(location: "Africa-Lagos", flag: 'ng.png', url: 'Africa/Lagos'),
  WorldTime(location: "Africa-Libreville", flag: 'ga.png', url: 'Africa/Libreville'),
  WorldTime(location: "Africa-Lome", flag: 'tg.png', url: 'Africa/Lome'),
  WorldTime(location: "Africa-Luanda", flag: 'ao.png', url: 'Africa/Luanda'),
  WorldTime(location: "Africa-Lubumbashi", flag: 'cd.png', url: 'Africa/Lubumbashi'),
  WorldTime(location: "Africa-Lusaka", flag: 'zm.png', url: 'Africa/Lusaka'),
  WorldTime(location: "Africa-Malabo", flag: 'gq.png', url: 'Africa/Malabo'),
  WorldTime(location: "Africa-Maputo", flag: 'mz.png', url: 'Africa/Maputo'),
  WorldTime(location: "Africa-Maseru", flag: 'ls.png', url: 'Africa/Maseru'),
  WorldTime(location: "Africa-Mbabane", flag: 'sz.png', url: 'Africa/Mbabane'),
  WorldTime(location: "Africa-Mogadishu", flag: 'so.png', url: 'Africa/Mogadishu'),
  WorldTime(location: "Africa-Monrovia", flag: 'lr.png', url: 'Africa/Monrovia'),
  WorldTime(location: "Africa-Nairobi", flag: 'ke.png', url: 'Africa/Nairobi'),
  WorldTime(location: "Africa-Ndjamena", flag: 'td.png', url: 'Africa/Ndjamena'),
  WorldTime(location: "Africa-Niamey", flag: 'ne.png', url: 'Africa/Niamey'),
  WorldTime(location: "Africa-Nouakchott", flag: 'mr.png', url: 'Africa/Nouakchott'),
  WorldTime(location: "Africa-Ouagadougou", flag: 'bf.png', url: 'Africa/Ouagadougou'),
  WorldTime(location: "Africa-Porto-Novo", flag: 'bj.png', url: 'Africa/Porto-Novo'),
  WorldTime(location: "Africa-Sao Tome", flag: 'st.png', url: 'Africa/Sao_Tome'),
  WorldTime(location: "Africa-Tripoli", flag: 'ly.png', url: 'Africa/Tripoli'),
  WorldTime(location: "Africa-Tunis", flag: 'tn.png', url: 'Africa/Tunis'),
  WorldTime(location: "Africa-Windhoek", flag: 'na.png', url: 'Africa/Windhoek'),
  WorldTime(location: "America-Adak", flag: 'us.png', url: 'America/Adak'),
  WorldTime(location: "America-Anchorage", flag: 'us.png', url: 'America/Anchorage'),
  WorldTime(location: "America-Anguilla", flag: 'ai.png', url: 'America/Anguilla'),
  WorldTime(location: "America-Antigua", flag: 'ag.png', url: 'America/Antigua'),
  WorldTime(location: "America-Araguaina", flag: 'br.png', url: 'America/Araguaina'),
  WorldTime(location: "America-Buenos Aires", flag: 'ar.png', url: 'America/Argentina/Buenos_Aires'),
  WorldTime(location: "America-Catamarca", flag: 'ar.png', url: 'America/Argentina/Catamarca'),
  WorldTime(location: "America-Cordoba", flag: 'ar.png', url: 'America/Argentina/Cordoba'),
  WorldTime(location: "America-Jujuy", flag: 'ar.png', url: 'America/Argentina/Jujuy'),
  WorldTime(location: "America-La Rioja", flag: 'ar.png', url: 'America/Argentina/La_Rioja'),
  WorldTime(location: "America-Mendoza", flag: 'ar.png', url: 'America/Argentina/Mendoza'),
  WorldTime(location: "America-Rio Gallegos", flag: 'ar.png', url: 'America/Argentina/Rio_Gallegos'),
  WorldTime(location: "America-Salta", flag: 'ar.png', url: 'America/Argentina/Salta'),
  WorldTime(location: "America-San Juan", flag: 'ar.png', url: 'America/Argentina/San_Juan'),
  WorldTime(location: "America-San Luis", flag: 'ar.png', url: 'America/Argentina/San_Luis'),
  WorldTime(location: "America-Tucuman", flag: 'ar.png', url: 'America/Argentina/Tucuman'),
  WorldTime(location: "America-Ushuaia", flag: 'ar.png', url: 'America/Argentina/Ushuaia'),
  WorldTime(location: "America-Aruba", flag: 'aw.png', url: 'America/Aruba'),
  WorldTime(location: "America-Asuncion", flag: 'py.png', url: 'America/Asuncion'),
  WorldTime(location: "America-Atikokan", flag: 'ca.png', url: 'America/Atikokan'),
  WorldTime(location: "America-Bahia", flag: 'br.png', url: 'America/Bahia'),
  WorldTime(location: "America-Bahia Banderas", flag: 'mx.png', url: 'America/Bahia_Banderas'),
  WorldTime(location: "America-Barbados", flag: 'bb.png', url: 'America/Barbados'),
  WorldTime(location: "America-Belem", flag: 'br.png', url: 'America/Belem'),
  WorldTime(location: "America-Belize", flag: 'bz.png', url: 'America/Belize'),
  WorldTime(location: "America-Blanc-Sablon", flag: 'ca.png', url: 'America/Blanc-Sablon'),
  WorldTime(location: "America-Boa Vista", flag: 'br.png', url: 'America/Boa_Vista'),
  WorldTime(location: "America-Bogota", flag: 'co.png', url: 'America/Bogota'),
  WorldTime(location: "America-Boise", flag: 'us.png', url: 'America/Boise'),
  WorldTime(location: "America-Cambridge Bay", flag: 'ca.png', url: 'America/Cambridge_Bay'),
  WorldTime(location: "America-Campo Grande", flag: 'br.png', url: 'America/Campo_Grande'),
  WorldTime(location: "America-Cancun", flag: 'mx.png', url: 'America/Cancun'),
  WorldTime(location: "America-Caracas", flag: 've.png', url: 'America/Caracas'),
  WorldTime(location: "America-Cayenne", flag: 'gf.png', url: 'America/Cayenne'),
  WorldTime(location: "America-Cayman", flag: 'ky.png', url: 'America/Cayman'),
  WorldTime(location: "America-Chicago", flag: 'us.png', url: 'America/Chicago'),
  WorldTime(location: "America-Chihuahua", flag: 'mx.png', url: 'America/Chihuahua'),
  WorldTime(location: "America-Costa Rica", flag: 'cr.png', url: 'America/Costa_Rica'),
  WorldTime(location: "America-Creston", flag: 'ca.png', url: 'America/Creston'),
  WorldTime(location: "America-Cuiaba", flag: 'br.png', url: 'America/Cuiaba'),
  WorldTime(location: "America-Curacao", flag: 'cw.png', url: 'America/Curacao'),
  WorldTime(location: "America-Danmarkshavn", flag: 'gl.png', url: 'America/Danmarkshavn'),
  WorldTime(location: "America-Dawson", flag: 'ca.png', url: 'America/Dawson'),
  WorldTime(location: "America-Dawson Creek", flag: 'ca.png', url: 'America/Dawson_Creek'),
  WorldTime(location: "America-Denver", flag: 'us.png', url: 'America/Denver'),
  WorldTime(location: "America-Detroit", flag: 'us.png', url: 'America/Detroit'),
  WorldTime(location: "America-Dominica", flag: 'dm.png', url: 'America/Dominica'),
  WorldTime(location: "America-Edmonton", flag: 'ca.png', url: 'America/Edmonton'),
  WorldTime(location: "America-Eirunepe", flag: 'br.png', url: 'America/Eirunepe'),
  WorldTime(location: "America-El Salvador", flag: 'sv.png', url: 'America/El_Salvador'),
  WorldTime(location: "America-Fort Nelson", flag: 'ca.png', url: 'America/Fort_Nelson'),
  WorldTime(location: "America-Fortaleza", flag: 'br.png', url: 'America/Fortaleza'),
  WorldTime(location: "America-Glace Bay", flag: 'ca.png', url: 'America/Glace_Bay'),
  WorldTime(location: "America-Goose Bay", flag: 'ca.png', url: 'America/Goose_Bay'),
  WorldTime(location: "America-Grand Turk", flag: 'tc.png', url: 'America/Grand_Turk'),
  WorldTime(location: "America-Grenada", flag: 'gd.png', url: 'America/Grenada'),
  WorldTime(location: "America-Guadeloupe", flag: 'gp.png', url: 'America/Guadeloupe'),
  WorldTime(location: "America-Guatemala", flag: 'gt.png', url: 'America/Guatemala'),
  WorldTime(location: "America-Guayaquil", flag: 'ec.png', url: 'America/Guayaquil'),
  WorldTime(location: "America-Guyana", flag: 'gy.png', url: 'America/Guyana'),
  WorldTime(location: "America-Halifax", flag: 'ca.png', url: 'America/Halifax'),
  WorldTime(location: "America-Havana", flag: 'cu.png', url: 'America/Havana'),
  WorldTime(location: "America-Hermosillo", flag: 'mx.png', url: 'America/Hermosillo'),
  WorldTime(location: "America-Indianapolis", flag: 'us.png', url: 'America/Indiana/Indianapolis'),
  WorldTime(location: "America-Knox", flag: 'us.png', url: 'America/Indiana/Knox'),
  WorldTime(location: "America-Marengo", flag: 'us.png', url: 'America/Indiana/Marengo'),
  WorldTime(location: "America-Petersburg", flag: 'us.png', url: 'America/Indiana/Petersburg'),
  WorldTime(location: "America-Tell City", flag: 'us.png', url: 'America/Indiana/Tell_City'),
  WorldTime(location: "America-Vevay", flag: 'us.png', url: 'America/Indiana/Vevay'),
  WorldTime(location: "America-Vincennes", flag: 'us.png', url: 'America/Indiana/Vincennes'),
  WorldTime(location: "America-Winamac", flag: 'us.png', url: 'America/Indiana/Winamac'),
  WorldTime(location: "America-Inuvik", flag: 'ca.png', url: 'America/Inuvik'),
  WorldTime(location: "America-Iqaluit", flag: 'ca.png', url: 'America/Iqaluit'),
  WorldTime(location: "America-Jamaica", flag: 'jm.png', url: 'America/Jamaica'),
  WorldTime(location: "America-Juneau", flag: 'us.png', url: 'America/Juneau'),
  WorldTime(location: "America-Louisville", flag: 'us.png', url: 'America/Kentucky/Louisville'),
  WorldTime(location: "America-Monticello", flag: 'us.png', url: 'America/Kentucky/Monticello'),
  WorldTime(location: "America-La Paz", flag: 'bo.png', url: 'America/La_Paz'),
  WorldTime(location: "America-Lima", flag: 'pe.png', url: 'America/Lima'),
  WorldTime(location: "America-Los Angeles", flag: 'us.png', url: 'America/Los_Angeles'),
  WorldTime(location: "America-Lower Princes", flag: 'sx.png', url: 'America/Lower_Princes'),
  WorldTime(location: "America-Maceio", flag: 'br.png', url: 'America/Maceio'),
  WorldTime(location: "America-Managua", flag: 'ni.png', url: 'America/Managua'),
  WorldTime(location: "America-Manaus", flag: 'br.png', url: 'America/Manaus'),
  WorldTime(location: "America-Marigot", flag: 'mf.png', url: 'America/Marigot'),
  WorldTime(location: "America-Martinique", flag: 'mq.png', url: 'America/Martinique'),
  WorldTime(location: "America-Matamoros", flag: 'mx.png', url: 'America/Matamoros'),
  WorldTime(location: "America-Mazatlan", flag: 'mx.png', url: 'America/Mazatlan'),
  WorldTime(location: "America-Menominee", flag: 'us.png', url: 'America/Menominee'),
  WorldTime(location: "America-Merida", flag: 'mx.png', url: 'America/Merida'),
  WorldTime(location: "America-Metlakatla", flag: 'us.png', url: 'America/Metlakatla'),
  WorldTime(location: "America-Mexico City", flag: 'mx.png', url: 'America/Mexico_City'),
  WorldTime(location: "America-Miquelon", flag: 'pm.png', url: 'America/Miquelon'),
  WorldTime(location: "America-Moncton", flag: 'ca.png', url: 'America/Moncton'),
  WorldTime(location: "America-Monterrey", flag: 'mx.png', url: 'America/Monterrey'),
  WorldTime(location: "America-Montevideo", flag: 'uy.png', url: 'America/Montevideo'),
  WorldTime(location: "America-Montserrat", flag: 'ms.png', url: 'America/Montserrat'),
  WorldTime(location: "America-Nassau", flag: 'bs.png', url: 'America/Nassau'),
  WorldTime(location: "America-New York", flag: 'us.png', url: 'America/New_York'),
  WorldTime(location: "America-Nipigon", flag: 'ca.png', url: 'America/Nipigon'),
  WorldTime(location: "America-Nome", flag: 'us.png', url: 'America/Nome'),
  WorldTime(location: "America-Noronha", flag: 'br.png', url: 'America/Noronha'),
  WorldTime(location: "America-Beulah", flag: 'us.png', url: 'America/North_Dakota/Beulah'),
  WorldTime(location: "America-Center", flag: 'us.png', url: 'America/North_Dakota/Center'),
  WorldTime(location: "America-New Salem", flag: 'us.png', url: 'America/North_Dakota/New_Salem'),
  WorldTime(location: "America-Nuuk", flag: 'gl.png', url: 'America/Nuuk'),
  WorldTime(location: "America-Ojinaga", flag: 'mx.png', url: 'America/Ojinaga'),
  WorldTime(location: "America-Panama", flag: 'pa.png', url: 'America/Panama'),
  WorldTime(location: "America-Paramaribo", flag: 'sr.png', url: 'America/Paramaribo'),
  WorldTime(location: "America-Phoenix", flag: 'us.png', url: 'America/Phoenix'),
  WorldTime(location: "America-Port-au-Prince", flag: 'ht.png', url: 'America/Port-au-Prince'),
  WorldTime(location: "America-Port of Spain", flag: 'tt.png', url: 'America/Port_of_Spain'),
  WorldTime(location: "America-Porto Velho", flag: 'br.png', url: 'America/Porto_Velho'),
  WorldTime(location: "America-Puerto Rico", flag: 'pr.png', url: 'America/Puerto_Rico'),
  WorldTime(location: "America-Punta Arenas", flag: 'cl.png', url: 'America/Punta_Arenas'),
  WorldTime(location: "America-Rainy River", flag: 'ca.png', url: 'America/Rainy_River'),
  WorldTime(location: "America-Rankin Inlet", flag: 'ca.png', url: 'America/Rankin_Inlet'),
  WorldTime(location: "America-Recife", flag: 'br.png', url: 'America/Recife'),
  WorldTime(location: "America-Regina", flag: 'ca.png', url: 'America/Regina'),
  WorldTime(location: "America-Resolute", flag: 'ca.png', url: 'America/Resolute'),
  WorldTime(location: "America-Rio Branco", flag: 'br.png', url: 'America/Rio_Branco'),
  WorldTime(location: "America-Santarem", flag: 'br.png', url: 'America/Santarem'),
  WorldTime(location: "America-Santiago", flag: 'cl.png', url: 'America/Santiago'),
  WorldTime(location: "America-Santo Domingo", flag: 'do.png', url: 'America/Santo_Domingo'),
  WorldTime(location: "America-Sao Paulo", flag: 'br.png', url: 'America/Sao_Paulo'),
  WorldTime(location: "America-Scoresbysund", flag: 'gl.png', url: 'America/Scoresbysund'),
  WorldTime(location: "America-Sitka", flag: 'us.png', url: 'America/Sitka'),
  WorldTime(location: "America-St Barthelemy", flag: 'bl.png', url: 'America/St_Barthelemy'),
  WorldTime(location: "America-St Johns", flag: 'ca.png', url: 'America/St_Johns'),
  WorldTime(location: "America-St Kitts", flag: 'kn.png', url: 'America/St_Kitts'),
  WorldTime(location: "America-St Lucia", flag: 'lc.png', url: 'America/St_Lucia'),
  WorldTime(location: "America-St Thomas", flag: 'vi.png', url: 'America/St_Thomas'),
  WorldTime(location: "America-St Vincent", flag: 'vc.png', url: 'America/St_Vincent'),
  WorldTime(location: "America-Swift Current", flag: 'ca.png', url: 'America/Swift_Current'),
  WorldTime(location: "America-Tegucigalpa", flag: 'hn.png', url: 'America/Tegucigalpa'),
  WorldTime(location: "America-Thule", flag: 'gl.png', url: 'America/Thule'),
  WorldTime(location: "America-Tijuana", flag: 'mx.png', url: 'America/Tijuana'),
  WorldTime(location: "America-Toronto", flag: 'ca.png', url: 'America/Toronto'),
  WorldTime(location: "America-Tortola", flag: 'vg.png', url: 'America/Tortola'),
  WorldTime(location: "America-Vancouver", flag: 'ca.png', url: 'America/Vancouver'),
  WorldTime(location: "America-Whitehorse", flag: 'ca.png', url: 'America/Whitehorse'),
  WorldTime(location: "America-Winnipeg", flag: 'ca.png', url: 'America/Winnipeg'),
  WorldTime(location: "America-Yakutat", flag: 'us.png', url: 'America/Yakutat'),
  WorldTime(location: "America-Yellowknife", flag: 'ca.png', url: 'America/Yellowknife'),
  WorldTime(location: "Antarctica-Casey", flag: 'aq.png', url: 'Antarctica/Casey'),
  WorldTime(location: "Antarctica-Davis", flag: 'aq.png', url: 'Antarctica/Davis'),
  WorldTime(location: "Antarctica-DumontDUrville", flag: 'aq.png', url: 'Antarctica/DumontDUrville'),
  WorldTime(location: "Antarctica-Macquarie", flag: 'aq.png', url: 'Antarctica/Macquarie'),
  WorldTime(location: "Antarctica-Mawson", flag: 'aq.png', url: 'Antarctica/Mawson'),
  WorldTime(location: "Antarctica-Palmer", flag: 'aq.png', url: 'Antarctica/Palmer'),
  WorldTime(location: "Antarctica-Rothera", flag: 'aq.png', url: 'Antarctica/Rothera'),
  WorldTime(location: "Antarctica-Syowa", flag: 'aq.png', url: 'Antarctica/Syowa'),
  WorldTime(location: "Antarctica-Troll", flag: 'aq.png', url: 'Antarctica/Troll'),
  WorldTime(location: "Antarctica-Vostok", flag: 'aq.png', url: 'Antarctica/Vostok'),
  WorldTime(location: "Arctic-Longyearbyen", flag: 'sj.png', url: 'Arctic/Longyearbyen'),
  WorldTime(location: "Asia-Aden", flag: 'ye.png', url: 'Asia/Aden'),
  WorldTime(location: "Asia-Almaty", flag: 'kz.png', url: 'Asia/Almaty'),
  WorldTime(location: "Asia-Amman", flag: 'jo.png', url: 'Asia/Amman'),
  WorldTime(location: "Asia-Anadyr", flag: 'ru.png', url: 'Asia/Anadyr'),
  WorldTime(location: "Asia-Aqtau", flag: 'kz.png', url: 'Asia/Aqtau'),
  WorldTime(location: "Asia-Aqtobe", flag: 'kz.png', url: 'Asia/Aqtobe'),
  WorldTime(location: "Asia-Ashgabat", flag: 'tm.png', url: 'Asia/Ashgabat'),
  WorldTime(location: "Asia-Atyrau", flag: 'kz.png', url: 'Asia/Atyrau'),
  WorldTime(location: "Asia-Baghdad", flag: 'iq.png', url: 'Asia/Baghdad'),
  WorldTime(location: "Asia-Bahrain", flag: 'bh.png', url: 'Asia/Bahrain'),
  WorldTime(location: "Asia-Baku", flag: 'az.png', url: 'Asia/Baku'),
  WorldTime(location: "Asia-Bangkok", flag: 'th.png', url: 'Asia/Bangkok'),
  WorldTime(location: "Asia-Barnaul", flag: 'ru.png', url: 'Asia/Barnaul'),
  WorldTime(location: "Asia-Beirut", flag: 'lb.png', url: 'Asia/Beirut'),
  WorldTime(location: "Asia-Bishkek", flag: 'kg.png', url: 'Asia/Bishkek'),
  WorldTime(location: "Asia-Brunei", flag: 'bn.png', url: 'Asia/Brunei'),
  WorldTime(location: "Asia-Calcutta", flag: 'in.png', url: 'Asia/Calcutta'),
  WorldTime(location: "Asia-Chita", flag: 'ru.png', url: 'Asia/Chita'),
  WorldTime(location: "Asia-Choibalsan", flag: 'mn.png', url: 'Asia/Choibalsan'),
  WorldTime(location: "Asia-Colombo", flag: 'lk.png', url: 'Asia/Colombo'),
  WorldTime(location: "Asia-Damascus", flag: 'sy.png', url: 'Asia/Damascus'),
  WorldTime(location: "Asia-Dhaka", flag: 'bd.png', url: 'Asia/Dhaka'),
  WorldTime(location: "Asia-Dili", flag: 'tl.png', url: 'Asia/Dili'),
  WorldTime(location: "Asia-Dubai", flag: 'ae.png', url: 'Asia/Dubai'),
  WorldTime(location: "Asia-Dushanbe", flag: 'tj.png', url: 'Asia/Dushanbe'),
  WorldTime(location: "Asia-Famagusta", flag: 'cy.png', url: 'Asia/Famagusta'),
  WorldTime(location: "Asia-Gaza", flag: 'ps.png', url: 'Asia/Gaza'),
  WorldTime(location: "Asia-Hebron", flag: 'ps.png', url: 'Asia/Hebron'),
  WorldTime(location: "Asia-Ho Chi Minh", flag: 'vn.png', url: 'Asia/Ho_Chi_Minh'),
  WorldTime(location: "Asia-Hong Kong", flag: 'hk.png', url: 'Asia/Hong_Kong'),
  WorldTime(location: "Asia-Hovd", flag: 'mn.png', url: 'Asia/Hovd'),
  WorldTime(location: "Asia-Irkutsk", flag: 'ru.png', url: 'Asia/Irkutsk'),
  WorldTime(location: "Asia-Jakarta", flag: 'id.png', url: 'Asia/Jakarta'),
  WorldTime(location: "Asia-Jayapura", flag: 'id.png', url: 'Asia/Jayapura'),
  WorldTime(location: "Asia-Jerusalem", flag: 'il.png', url: 'Asia/Jerusalem'),
  WorldTime(location: "Asia-Kabul", flag: 'af.png', url: 'Asia/Kabul'),
  WorldTime(location: "Asia-Kamchatka", flag: 'ru.png', url: 'Asia/Kamchatka'),
  WorldTime(location: "Asia-Karachi", flag: 'pk.png', url: 'Asia/Karachi'),
  WorldTime(location: "Asia-Kathmandu", flag: 'np.png', url: 'Asia/Kathmandu'),
  WorldTime(location: "Asia-Khandyga", flag: 'ru.png', url: 'Asia/Khandyga'),
  WorldTime(location: "Asia-Krasnoyarsk", flag: 'ru.png', url: 'Asia/Krasnoyarsk'),
  WorldTime(location: "Asia-Kuala Lumpur", flag: 'my.png', url: 'Asia/Kuala_Lumpur'),
  WorldTime(location: "Asia-Kuching", flag: 'my.png', url: 'Asia/Kuching'),
  WorldTime(location: "Asia-Kuwait", flag: 'kw.png', url: 'Asia/Kuwait'),
  WorldTime(location: "Asia-Macau", flag: 'mo.png', url: 'Asia/Macau'),
  WorldTime(location: "Asia-Magadan", flag: 'ru.png', url: 'Asia/Magadan'),
  WorldTime(location: "Asia-Makassar", flag: 'id.png', url: 'Asia/Makassar'),
  WorldTime(location: "Asia-Manila", flag: 'ph.png', url: 'Asia/Manila'),
  WorldTime(location: "Asia-Nicosia", flag: 'cy.png', url: 'Asia/Nicosia'),
  WorldTime(location: "Asia-Novokuznetsk", flag: 'ru.png', url: 'Asia/Novokuznetsk'),
  WorldTime(location: "Asia-Novosibirsk", flag: 'ru.png', url: 'Asia/Novosibirsk'),
  WorldTime(location: "Asia-Omsk", flag: 'ru.png', url: 'Asia/Omsk'),
  WorldTime(location: "Asia-Oral", flag: 'kz.png', url: 'Asia/Oral'),
  WorldTime(location: "Asia-Phnom Penh", flag: 'kh.png', url: 'Asia/Phnom_Penh'),
  WorldTime(location: "Asia-Pontianak", flag: 'id.png', url: 'Asia/Pontianak'),
  WorldTime(location: "Asia-Pyongyang", flag: 'kp.png', url: 'Asia/Pyongyang'),
  WorldTime(location: "Asia-Qatar", flag: 'qa.png', url: 'Asia/Qatar'),
  WorldTime(location: "Asia-Qostanay", flag: 'kz.png', url: 'Asia/Qostanay'),
  WorldTime(location: "Asia-Qyzylorda", flag: 'kz.png', url: 'Asia/Qyzylorda'),
  WorldTime(location: "Asia-Riyadh", flag: 'sa.png', url: 'Asia/Riyadh'),
  WorldTime(location: "Asia-Sakhalin", flag: 'ru.png', url: 'Asia/Sakhalin'),
  WorldTime(location: "Asia-Samarkand", flag: 'uz.png', url: 'Asia/Samarkand'),
  WorldTime(location: "Asia-Seoul", flag: 'kr.png', url: 'Asia/Seoul'),
  WorldTime(location: "Asia-Shanghai", flag: 'cn.png', url: 'Asia/Shanghai'),
  WorldTime(location: "Asia-Singapore", flag: 'sg.png', url: 'Asia/Singapore'),
  WorldTime(location: "Asia-Srednekolymsk", flag: 'ru.png', url: 'Asia/Srednekolymsk'),
  WorldTime(location: "Asia-Taipei", flag: 'tw.png', url: 'Asia/Taipei'),
  WorldTime(location: "Asia-Tashkent", flag: 'uz.png', url: 'Asia/Tashkent'),
  WorldTime(location: "Asia-Tbilisi", flag: 'ge.png', url: 'Asia/Tbilisi'),
  WorldTime(location: "Asia-Tehran", flag: 'ir.png', url: 'Asia/Tehran'),
  WorldTime(location: "Asia-Thimphu", flag: 'bt.png', url: 'Asia/Thimphu'),
  WorldTime(location: "Asia-Tokyo", flag: 'jp.png', url: 'Asia/Tokyo'),
  WorldTime(location: "Asia-Tomsk", flag: 'ru.png', url: 'Asia/Tomsk'),
  WorldTime(location: "Asia-Ulaanbaatar", flag: 'mn.png', url: 'Asia/Ulaanbaatar'),
  WorldTime(location: "Asia-Urumqi", flag: 'cn.png', url: 'Asia/Urumqi'),
  WorldTime(location: "Asia-Ust-Nera", flag: 'ru.png', url: 'Asia/Ust-Nera'),
  WorldTime(location: "Asia-Vientiane", flag: 'la.png', url: 'Asia/Vientiane'),
  WorldTime(location: "Asia-Vladivostok", flag: 'ru.png', url: 'Asia/Vladivostok'),
  WorldTime(location: "Asia-Yakutsk", flag: 'ru.png', url: 'Asia/Yakutsk'),
  WorldTime(location: "Asia-Yangon", flag: 'mm.png', url: 'Asia/Yangon'),
  WorldTime(location: "Asia-Yekaterinburg", flag: 'ru.png', url: 'Asia/Yekaterinburg'),
  WorldTime(location: "Asia-Yerevan", flag: 'am.png', url: 'Asia/Yerevan'),
  WorldTime(location: "Atlantic-Azores", flag: 'pt.png', url: 'Atlantic/Azores'),
  WorldTime(location: "Atlantic-Bermuda", flag: 'bm.png', url: 'Atlantic/Bermuda'),
  WorldTime(location: "Atlantic-Canary", flag: 'es.png', url: 'Atlantic/Canary'),
  WorldTime(location: "Atlantic-Cape Verde", flag: 'cv.png', url: 'Atlantic/Cape_Verde'),
  WorldTime(location: "Atlantic-Faroe", flag: 'fo.png', url: 'Atlantic/Faroe'),
  WorldTime(location: "Atlantic-Madeira", flag: 'pt.png', url: 'Atlantic/Madeira'),
  WorldTime(location: "Atlantic-Reykjavik", flag: 'is.png', url: 'Atlantic/Reykjavik'),
  WorldTime(location: "Atlantic-South Georgia", flag: 'gs.png', url: 'Atlantic/South_Georgia'),
  WorldTime(location: "Atlantic-St Helena", flag: 'sh.png', url: 'Atlantic/St_Helena'),
  WorldTime(location: "Atlantic-Stanley", flag: 'fk.png', url: 'Atlantic/Stanley'),
  WorldTime(location: "Australia-Adelaide", flag: 'au.png', url: 'Australia/Adelaide'),
  WorldTime(location: "Australia-Brisbane", flag: 'au.png', url: 'Australia/Brisbane'),
  WorldTime(location: "Australia-Broken Hill", flag: 'au.png', url: 'Australia/Broken_Hill'),
  WorldTime(location: "Australia-Currie", flag: 'au.png', url: 'Australia/Currie'),
  WorldTime(location: "Australia-Darwin", flag: 'au.png', url: 'Australia/Darwin'),
  WorldTime(location: "Australia-Eucla", flag: 'au.png', url: 'Australia/Eucla'),
  WorldTime(location: "Australia-Hobart", flag: 'au.png', url: 'Australia/Hobart'),
  WorldTime(location: "Australia-Lindeman", flag: 'au.png', url: 'Australia/Lindeman'),
  WorldTime(location: "Australia-Lord Howe", flag: 'au.png', url: 'Australia/Lord_Howe'),
  WorldTime(location: "Australia-Melbourne", flag: 'au.png', url: 'Australia/Melbourne'),
  WorldTime(location: "Australia-Perth", flag: 'au.png', url: 'Australia/Perth'),
  WorldTime(location: "Australia-Sydney", flag: 'au.png', url: 'Australia/Sydney'),
  WorldTime(location: "Europe-Amsterdam", flag: 'nl.png', url: 'Europe/Amsterdam'),
  WorldTime(location: "Europe-Andorra", flag: 'ad.png', url: 'Europe/Andorra'),
  WorldTime(location: "Europe-Astrakhan", flag: 'ru.png', url: 'Europe/Astrakhan'),
  WorldTime(location: "Europe-Athens", flag: 'gr.png', url: 'Europe/Athens'),
  WorldTime(location: "Europe-Belgrade", flag: 'rs.png', url: 'Europe/Belgrade'),
  WorldTime(location: "Europe-Berlin", flag: 'de.png', url: 'Europe/Berlin'),
  WorldTime(location: "Europe-Bratislava", flag: 'sk.png', url: 'Europe/Bratislava'),
  WorldTime(location: "Europe-Brussels", flag: 'be.png', url: 'Europe/Brussels'),
  WorldTime(location: "Europe-Bucharest", flag: 'ro.png', url: 'Europe/Bucharest'),
  WorldTime(location: "Europe-Budapest", flag: 'hu.png', url: 'Europe/Budapest'),
  WorldTime(location: "Europe-Busingen", flag: 'de.png', url: 'Europe/Busingen'),
  WorldTime(location: "Europe-Chisinau", flag: 'md.png', url: 'Europe/Chisinau'),
  WorldTime(location: "Europe-Copenhagen", flag: 'dk.png', url: 'Europe/Copenhagen'),
  WorldTime(location: "Europe-Dublin", flag: 'ie.png', url: 'Europe/Dublin'),
  WorldTime(location: "Europe-Gibraltar", flag: 'gi.png', url: 'Europe/Gibraltar'),
  WorldTime(location: "Europe-Guernsey", flag: 'gg.png', url: 'Europe/Guernsey'),
  WorldTime(location: "Europe-Helsinki", flag: 'fi.png', url: 'Europe/Helsinki'),
  WorldTime(location: "Europe-Isle of Man", flag: 'im.png', url: 'Europe/Isle_of_Man'),
  WorldTime(location: "Europe-Istanbul", flag: 'tr.png', url: 'Europe/Istanbul'),
  WorldTime(location: "Europe-Jersey", flag: 'je.png', url: 'Europe/Jersey'),
  WorldTime(location: "Europe-Kaliningrad", flag: 'ru.png', url: 'Europe/Kaliningrad'),
  WorldTime(location: "Europe-Kaliningrad", flag: 'ru.png', url: 'Europe/Kaliningrad'),
  WorldTime(location: "Europe-Kiev", flag: 'ua.png', url: 'Europe/Kiev'),
  WorldTime(location: "Europe-Kirov", flag: 'ru.png', url: 'Europe/Kirov'),
  WorldTime(location: "Europe-Lisbon", flag: 'pt.png', url: 'Europe/Lisbon'),
  WorldTime(location: "Europe-Ljubljana", flag: 'si.png', url: 'Europe/Ljubljana'),
  WorldTime(location: "Europe-London", flag: 'gb.png', url: 'Europe/London'),
  WorldTime(location: "Europe-Luxembourg", flag: 'lu.png', url: 'Europe/Luxembourg'),
  WorldTime(location: "Europe-Madrid", flag: 'es.png', url: 'Europe/Madrid'),
  WorldTime(location: "Europe-Malta", flag: 'mt.png', url: 'Europe/Malta'),
  WorldTime(location: "Europe-Mariehamn", flag: 'ax.png', url: 'Europe/Mariehamn'),
  WorldTime(location: "Europe-Minsk", flag: 'by.png', url: 'Europe/Minsk'),
  WorldTime(location: "Europe-Monaco", flag: 'mc.png', url: 'Europe/Monaco'),
  WorldTime(location: "Europe-Moscow", flag: 'ru.png', url: 'Europe/Moscow'),
  WorldTime(location: "Europe-Oslo", flag: 'no.png', url: 'Europe/Oslo'),
  WorldTime(location: "Europe-Paris", flag: 'fr.png', url: 'Europe/Paris'),
  WorldTime(location: "Europe-Podgorica", flag: 'me.png', url: 'Europe/Podgorica'),
  WorldTime(location: "Europe-Prague", flag: 'cz.png', url: 'Europe/Prague'),
  WorldTime(location: "Europe-Riga", flag: 'lv.png', url: 'Europe/Riga'),
  WorldTime(location: "Europe-Rome", flag: 'it.png', url: 'Europe/Rome'),
  WorldTime(location: "Europe-Samara", flag: 'ru.png', url: 'Europe/Samara'),
  WorldTime(location: "Europe-San Marino", flag: 'sm.png', url: 'Europe/San_Marino'),
  WorldTime(location: "Europe-Sarajevo", flag: 'ba.png', url: 'Europe/Sarajevo'),
  WorldTime(location: "Europe-Saratov", flag: 'ru.png', url: 'Europe/Saratov'),
  WorldTime(location: "Europe-Simferopol", flag: 'ua.png', url: 'Europe/Simferopol'),
  WorldTime(location: "Europe-Skopje", flag: 'mk.png', url: 'Europe/Skopje'),
  WorldTime(location: "Europe-Sofia", flag: 'bg.png', url: 'Europe/Sofia'),
  WorldTime(location: "Europe-Stockholm", flag: 'se.png', url: 'Europe/Stockholm'),
  WorldTime(location: "Europe-Tallinn", flag: 'ee.png', url: 'Europe/Tallinn'),
  WorldTime(location: "Europe-Tirane", flag: 'al.png', url: 'Europe/Tirane'),
  WorldTime(location: "Europe-Ulyanovsk", flag: 'ru.png', url: 'Europe/Ulyanovsk'),
  WorldTime(location: "Europe-Uzhgorod", flag: 'ua.png', url: 'Europe/Uzhgorod'),
  WorldTime(location: "Europe-Vaduz", flag: 'li.png', url: 'Europe/Vaduz'),
  WorldTime(location: "Europe-Vatican", flag: 'va.png', url: 'Europe/Vatican'),
  WorldTime(location: "Europe-Vienna", flag: 'at.png', url: 'Europe/Vienna'),
  WorldTime(location: "Europe-Vilnius", flag: 'lt.png', url: 'Europe/Vilnius'),
  WorldTime(location: "Europe-Volgograd", flag: 'ru.png', url: 'Europe/Volgograd'),
  WorldTime(location: "Europe-Warsaw", flag: 'pl.png', url: 'Europe/Warsaw'),
  WorldTime(location: "Europe-Zagreb", flag: 'hr.png', url: 'Europe/Zagreb'),
  WorldTime(location: "Europe-Zaporozhye", flag: 'ua.png', url: 'Europe/Zaporozhye'),
  WorldTime(location: "Europe-Zurich", flag: 'ch.png', url: 'Europe/Zurich'),
  ];

  void updateTime(index) async {
    WorldTime instance = locations[index];
    await instance.getTime();
    //navigate to home screen
    Navigator.pop(context, {
      'location': instance.location,
      'flag': instance.flag,
      'time': instance.time,
      'isDaytime': instance.isDaytime,
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey[200],
      appBar: AppBar(
        backgroundColor: Colors.blue[900],
        title: Text('Choose a Location'),
        centerTitle: true,
        elevation: 0,
      ),
      body: ListView.builder(
        itemCount: locations.length,
        itemBuilder: (context, index){
          return Padding(
            padding: const EdgeInsets.symmetric(vertical: 1.0, horizontal: 4.0),
            child: Card(
              child: ListTile(
                onTap: () {
                  updateTime(index);
                },
                title: Text(locations[index].location),
                leading: CircleAvatar(
                  backgroundImage: AssetImage('assets/${locations[index].flag}'),
                ),
              ),
            ),
          );
        },
      ),
    );
  }
}
